/*
**  Copyright (c) 2010-2017, Panasonic Corporation.
**
**  Permission to use, copy, modify, and/or distribute this software for any
**  purpose with or without fee is hereby granted, provided that the above
**  copyright notice and this permission notice appear in all copies.
**
**  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
**  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
**  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
**  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
**  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
**  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
**  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
*/

package org.opendof.example;

import org.opendof.core.oal.DOFInterface;
import org.opendof.core.oal.DOFInterfaceID;
import org.opendof.core.oal.DOFType;
import org.opendof.core.oal.value.DOFString;

// This is the file generated by the interface repository: https://interface.opendof.org/interface/opendof/1.00010000/1?2

/**
 * <b> Hello World </b><p>
 * Hello World! This interface has a single read-only property containing the popular phrase. <p>
 *
 * IID: [1:{00010000}] <p>
 *
 * <b> Properties </b><p>
 * Phrase
 * The phrase.
 * <ul>
 * <li> Read: true </li>
 * <li> Write: false </li>
 *
 * </ul>
 */
public class HelloWorldInterface {

    /**
     * <b> phrase </b><p>
     * A phrase.
     */
    public static final DOFType phrase = new DOFString.Type(106, 256);

    public static final int PHRASE_ITEM_ID = 0;

    /**
     *  Hello World InterfaceID
     */
    public static final DOFInterfaceID INTERFACEID = DOFInterfaceID.create("[1:{00010000}]");


    /**
     *  Hello World Definition
     */
    public static final DOFInterface DEFINITION = new DOFInterface.Builder( INTERFACEID )
        .addProperty( PHRASE_ITEM_ID, false, true, phrase )
        .build();
}
